# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe3ff5756a70a5b43169ca92007e4e0696bffca1e595cc8c1d0b2350408a5dd20d2a9dcee508884015ddf481fffe88d6498cefa7f33d0d07485796b5586a002

test:
  secret_key_base: 2f1030108ada609abc2df3e43ec8c39f322c84272f829c0183e82e75696e0f2257329b14da8a41eb894840c89da5f50c8e3797e53fc2b017bf2f91c6d42fb444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
